name: version_bump

on:
  workflow_dispatch:
    inputs:
      releaseKind:
        description: 'Kind of version bump'
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
        required: true
      real:
        description: 'Real release'
        type: boolean
        required: false

jobs:
  build:
    name: version bump
    # todo: add back
    # runs-on: ubuntu-20.04-xl
    runs-on: ubuntu-latest
    timeout-minutes: 90

    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: full
      RUSTC_FORCE_INCREMENTAL: 1

    steps:
      - name: Configure git
        run: |
          git config --global core.symlinks true
          git config --global fetch.parallel 32

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@stable

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.19.3

      - name: Run version bump
        run: |
          git remote add upstream https://github.com/denoland/deno
          ./tools/release/01_bump_crate_versions.ts --${{github.event.inputs.releaseKind}}

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          ./tools/release/02_commit_versions.ts

      # todo(https://github.com/rust-lang/cargo/issues/1169): enable
      # once cargo supports doing a dry publish for multiple
      # unpublished packages
      # - name: Dry publish
      #   run: ./tools/release/03_publish_crates.ts --dry

      - name: Create draft pull request
        if: ${{ github.event.inputs.real == 'true' }}
        uses: peter-evans/create-pull-request@v3
        with:
          base: ${{ github.ref }}
          draft: true
